spring:
  application:
    name: template-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8070

  # 解决Zipkin启动The bean 'characterEncodingFilter', defined in
  main:
    allow-bean-definition-overriding: true

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

management:
  metrics:
    web:
      # 解决Zipkin报错IllegalArgumentException: Prometheus requires that all meters
      server:
        auto-time-requests: false