server:
  port: 8030

spring:
  application:
    name: template-auth
  zipkin:
    base-url: http://localhost:8060
  boot:
    admin:
      client:
        url: http://localhost:8070

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8010/eureka/

feign:
  hystrix:
    # feign整合了Hystrix 开启Feign的Hystrix熔断器支持
    enabled: true