server:
  port: 8020

spring:
  application:
    name: template-admin
  zipkin:
    base-url: http://localhost:8060
  boot:
    admin:
      client:
        url: http://localhost:8070

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8010/eureka/