server:
  port: 8040

spring:
  zipkin:
    base-url: http://localhost:8060
  profiles:
    active: native
  cloud:
    config:
      uri: http://lisa:8050       # 配置服务中心的网址  如果修改了默认端口，客户端项目必须在bootstrap.yml中配置
      name: application-zuul      # 配置文件的前缀名
      profile: dev                # 配置文件的环境标识   dev:开发环境   test:测试环境  prod:生产环境
#      label:                     # 配置仓库的分支。如果是本地读取，可不配置