server:
  port: 8050

spring:
  application:
    name: template-config
  zipkin:
    base-url: http://localhost:8060
  boot:
    admin:
      client:
        url: http://localhost:8070

  # 获取本地配置文件，本身支持：本地储存、git远程、SVN
  profiles:
    active: native

  cloud:
    config:
      server:
        # 获取本地配置文件的位置 也可以采用从远程github、gitlab端读取
        native:
          search-locations: classpath:config/

  # 远程读取
#  cloud:
#    config:
#      label: master # 配置仓库的分支
#      server:
#        git:
          # 配置Git仓库地址，如果用Github需要加.git，如果用Gitlab则不需要
#          uri: https://github.com/xx/spring-cloud-config
#          search-paths: respo # 配置仓库路径
#          username: # 访问Git仓库的账号
#          password: # 访问Git仓库的密码

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8010/eureka/
